# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Dong Jin blog
paginate:       5
baseurl:        ""
url:            "https://chesterhow.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Gems
gems:
  - jekyll-paginate
