# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jin Dong
paginate:       15
baseurl:        ""
url:            "https://djdongjin.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# Gems
gems:
  - jekyll-paginate
